use_frameworks!

platform :ios, '8.0'

target 'LGPodsWorking_Example' do
  pod 'LGPodsWorking', :path => '../'

  target 'LGPodsWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
